const MJ_SECURITY_VAULT_THEME_VARIANT_KEY = 'MJ_SECURITY_VAULT_THEME_VARIANT_KEY';
const SERVER_BASE_URL = 'https://mjsecurityvault-api.onrender.com/api/v1';
export const MJ_SECURITY_VAULT_CONSTANTS = {MJ_SECURITY_VAULT_THEME_VARIANT_KEY, SERVER_BASE_URL};